name: Jetpack-Deploy

on:
  push:
    branches:
      - master # Change this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and package APK
        run: ./gradlew assembleDebug # Adjust the build command as needed

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can adjust the Node.js version

      - name: Install appcenter-cli
        run: npm install -g appcenter-cli

      - name: Upload APK to App Center
        run: |
          appcenter login --token "<env.APP_CENTER_TOKEN>"
          appcenter distribute release -f app/build/outputs/apk/debug/app-debug.apk -g <DISTRIBUTION_GROUPS>
