  name: Deploy-Android-TEST
  on: 
      workflow_dispatch:
      push:
        tags:
          - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'
  env:
    APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID_TEST  }}  
    APP_NAME: ${{ 'MyApp-Android/ENV_TEST'  }}  
    TESTING_GROUP: ${{  'ENV_TEST'  }} 
    UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }} 

  jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Clear npm cache
        run: npm cache clean --force

      - name: List directory contents
        run: ls -la JetpackPractice/JetpackPractice
          
      - name: Install dependencies
        run: npm install
      - name: Build android
        run: npm run cd android && ./gradlew assembleRelease
