name: Jetpack-Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID_TEST  }}  
  APP_NAME: ${{ 'kardas_dev/ENV_TEST'  }}  
  TESTING_GROUP: ${{  'ENV_TEST'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }}  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permissions to gradlew
        run: |
          chmod +x ./gradlew
    
      - name: Build android
        run: |
          ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
